public class TryCatch {
   public static void main(String args[]){
       try{
           int a[]=new int[2];
           a[4]=5/0;
       }
       catch(ArithmeticException e)
       {System.out.println("First Catch Block");}
       catch(ArrayIndexOutOfBoundsException e)
       {System.out.println("Second Catch Block");}
       catch(Exception e)
       {System.out.println("Third Catch Block");}
       finally
       {System.out.println("Finally Block Executed");}
   }
}

